### ISSUE TITLE
cannot modify unpublished entry

### ISSUE THREAD

**Issue by Anniepoo** [rla/blog-core#104]
seen 'in the wild', I haven't stopped to make a repro case (sorry) -

Started with 

https://github.com/StanfordOSAcademySWIProlog/website/commit/b8f973ca65adfe8654f90557d869be365d170cee

modified the intro page's contents

When I went to save it it complained of a lack of a publication date. I went back and checked published and it saved.

**Comment by rla** [comment]
Publish date is independent from Published flag. In order to show a post preview, publish date has to be filled in, otherwise it causes dict error when displaying the page (I did not find a better way to solve it). The idea is to keep HTML templates as minimal as possible and not have a huge nest of if/else's for missing data or post previews.

Version 0.0.3 fills in the date automatically when you create the post but when you edit posts from the older versions (where date was not required), they are not automatically filled. Instead, you get a notice to set it yourself.

I hope this clears up why it complained. The real issue is that post/page previews are not specified yet. My approach has been so far to check published flag in listings and NOT check it when displaying a singular entry page. Then previewing a post is just a matter of using the singular page URL with the post's slug.

**Comment by rla** [comment]
Closing as post previews come in the referenced issue.
