### ISSUE TITLE
Install error for swipl 7.1.28

### ISSUE THREAD

**Issue by bsoe003** [rla/blog-core#74]
I was attempting to 'pack_install' blog_core on swipl version 7.1.28 by calling 'pack_install(blog_core).' on swipl terminal. It gave me a following error:

ERROR: library `archive' does not exist
   Exception: (10) prolog_pack:pack_archive_info('/Users/bsoe/lib/swipl/pack/Downloads/blog_core-0.0.1.tgz', blog_core, _G2985, _G2986) ?

Any ideas how to fix this issue?

**Comment by rla** [comment]
This happens when the "built-in" archive library is not installed with SWI-Prolog. If you installed SWI from source, you need to make sure the configure script finds libarchive headers. Usually this is solved by installing `libarchive-dev` or equivalent and rebuilding. As I cannot guess the OS, I have to give a bunch of links (if it's the OSX then the first link helps):

* <http://stackoverflow.com/questions/25498346/error-library-archive-does-not-exist-swi-prolog>
* <http://swi-prolog.996271.n3.nabble.com/ERROR-library-archive-does-not-exist-td13900.html>

**Comment by rla** [comment]
Closing as this is related to SWI packs functionality not the Blog-Core itself.
